version: '3.1'
services:
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 9999:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db